# Generated by Django 3.0.7 on 2020-06-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startedAt', models.DateTimeField(null=True)),
                ('finishedAt', models.DateTimeField(null=True)),
                ('config', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(null=True)),
                ('trainStart', models.DateTimeField(null=True)),
                ('trainEnd', models.DateTimeField(null=True)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuner.Iteration')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pip', models.CharField(max_length=100)),
                ('accuracy', models.CharField(max_length=100)),
                ('trainingTime', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuner.Model')),
            ],
        ),
        migrations.CreateModel(
            name='ParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuner.Model')),
            ],
            options={
                'unique_together': {('param', 'model')},
            },
        ),
    ]
